spring:
  redis:
    host: 192.168.81.128
    password: li774143844
    port: 6379
    jedis:
      pool:
              max-idle: 8
              min-idle: 0
              max-active: 8
              max-wait: -1ms

